name: All Labs Autotests and Linting

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov ruff biopython

      - name: Run Linter for Lab 1 (Ruff)
        run: ruff check lab1/lab1.py || true

      - name: Run tests for Lab 1
        run: pytest lab1/test_lab1.py

      - name: Run tests for Lab 2 Variant 1
        run: python -m pytest lab2/test_main_v1.py -v

      - name: Run tests for Lab 3
        run: python -m pytest lab3/test_main.py -v
      - name: Run tests for Lab 2 Variant 3
        run: python -m pytest lab2/test_main_v3.py -v


